### ISSUE TITLE
Cell Values

### ISSUE THREAD

**Issue by boboxx** [rahmaevao/JbdBms#2]
How can we read the cell values?

**Comment by rahmaevao** [comment]
Hi, to read the voltage on the cells you need to read the register 0x4. The register 0x03 is currently being read. It is also necessary to add a parser.
See [documentation of manufacture](https://cdn.hackaday.io/files/1628066965491904/LH_communication_protocol.xlsx)r.
P.S.
If you can add the code, then you can make a pull request, and if you can’t, then I can try to write the code.
However, if you want me to write the code, then you need to know that I do not have BMS on hand. This means that you will have to check my code and write about errors if they occur.

**Comment by rahmaevao** [comment]
> How can we read the cell values?

Hi, to read the voltage on the cells you need to read the register 0x4. The register 0x03 is currently being read. It is also necessary to add a parser.
See [documentation of manufacture](https://cdn.hackaday.io/files/1628066965491904/LH_communication_protocol.xlsx)r.
P.S.
If you can add the code, then you can make a pull request, and if you can’t, then I can try to write the code.
However, if you want me to write the code, then you need to know that I do not have BMS on hand. This means that you will have to check my code and write about errors if they occur.

**Comment by boboxx** [comment]
I have no clue how to do a pull request, I have never used git before!

I did add the cell value and a few other basic values. Here are the files. This was tested with a JBD-SP04S020-L4S-12A-B-U BMS
[JbdBms.zip](https://github.com/rahmaevao/JbdBms/files/4301319/JbdBms.zip)

**Comment by boboxx** [comment]
This capacity: 100.00
Current: 0.00
Voltage: 13.62
Protection state: 1
Cycle: 9
Temp1: 22.70
Temp2: 24.60

Number Of Cell: 4
Low: 3404
High: 3410
Diff: 6
Avg: 3406
Cell1: 3404
Cell2: 3406
Cell3: 3405
Cell4: 3410

**Comment by rahmaevao** [comment]
You're doing fine.
You wrote code in my style.
I accepted your pull request. Later I will update RAEDME, and library files.
Thanks for the input.

**Comment by swarvie** [comment]
Hi, I have loaded your code to my Ardunio Mega but I can't seem to get any data from my BMS. I only receive the following.

17:17:21.029 -> JBD bms driver
17:17:21.870 -> JBD bms driver
17:17:22.710 -> JBD bms driver
17:17:23.551 -> JBD bms driver
17:17:24.389 -> JBD bms driver
17:17:25.272 -> JBD bms driver
17:17:26.113 -> JBD bms driver
17:17:26.955 -> JBD bms driver

Are you able to confirm the correct wiring from the BMS to Arduino Mega. I'm current connecting RX to pin RX pin 10 & 10 TX ground to ground. I can communicate with my BMS via PC JDB Tools using the UART box but have no luck luck connecting to Arduino Mega. Do you have any pictures of the desired wiring please.
