### ISSUE TITLE
Raw readings

### ISSUE THREAD

**Issue by boboxx** [rahmaevao/JbdBms#4]
Do you now how we could return the raw value from the BMS? Similar to what we are sending? I'm having a strange issue and I would like to debug.

If I leave the delay to 5sec in the loop, values are returned correctly but if I change it to 10sec.

Output of 5sec:
JBD bms driver
This capacity: 92.00
Current: 0.00
Voltage: 13.40
Protection state: 0
Cycle: 9
Temp1: 20.50
Temp2: 24.10

Number Of Cell: 4
Low: 3350

High: 3351
Diff: 1
Avg: 3350
Cell1: 3350
Cell2: 3350
Cell3: 3351
Cell4: 3350

Output of 10 sec delay:
This capacity: 78.00

Current: 645790.00
Voltage: 0.00
Protection state: 64575
Cycle: 64319
Temp1: 545.60
Temp2: 1343.30

Communication error

**Comment by rahmaevao** [comment]
Can you show the main file?

**Comment by boboxx** [comment]
void loop() {
  Serial.println("Reading");
  if (myBms.readBmsData() == true)
  {
    Serial.print("This capacity: "); Serial.println(myBms.getChargePercentage());
    Serial.print("Current: "); Serial.println(myBms.getCurrent());
    Serial.print("Voltage: "); Serial.println(myBms.getVoltage());
    Serial.print("Protection state: "); Serial.println(myBms.getProtectionState());
    Serial.print("Cycle: "); Serial.println(myBms.getCycle());
    Serial.print("Temp1: "); Serial.println(myBms.getTemp1());
    Serial.print("Temp2: "); Serial.println(myBms.getTemp2());

    Serial.println();
  } else {
    Serial.println("Basic: Communication error");
    Serial.println();
  }

  if (myBms.readPackData() == true)
  {
    packCellInfoStruct packInfo = myBms.getPackCellInfo();

    Serial.print("Number Of Cell: "); Serial.println(packInfo.NumOfCells);
    Serial.print("Low: "); Serial.println(packInfo.CellLow);
    Serial.print("High: "); Serial.println(packInfo.CellHigh);
    Serial.print("Diff: "); Serial.println(packInfo.CellDiff);
    Serial.print("Avg: "); Serial.println(packInfo.CellAvg);

    //go trough individual cells
    for (byte i = 0; i < packInfo.NumOfCells; i++)
    {
      Serial.print("Cell"); Serial.print(i+1); Serial.print(": "); Serial.println(packInfo.CellVoltage[i]);
    }
    Serial.println();
  } else {
    Serial.println("Cell: Communication error");
    Serial.println();
  }
delay(10000);

}

**Comment by rahmaevao** [comment]
perhaps this is due to the fact that reading does not start from the moment of transmission.
in this case, you can set the error accumulation counter.
for (int i=0; i<5;i++) {
   if (myBms.readBmsData() == true){
        Serial.print("This capacity: ")....
         break;
        }
}

**Comment by boboxx** [comment]
that would be a work around for the retry but it looks like there is something else sent in as the Basic info will fail and the pack data will be invalid. (I only have 4 cell in my pack)

Basic: Communication error

Number Of Cell: 13
Low: 0

High: 34571
Diff: 34571
Avg: 3145
Cell1: 1338
Cell2: 0
Cell3: 25636
Cell4: 28000
Cell5: 9
Cell6: 10115
Cell7: 0
Cell8: 0
Cell9: 0
Cell10: 5468
Cell11: 772
Cell12: 523
Cell13: 34571

**Comment by rahmaevao** [comment]
Most likely you are right.
It would be great to connect the analyzer to the bus.

**Comment by boboxx** [comment]
Is there a way to return all the data that was read from readResponce() back over to the loop so it can be displayed?

**Comment by rahmaevao** [comment]
Did I understand correctly that:
- reads well first
- after 10 seconds strange data
- after another 10 seconds, a read error?

**Comment by boboxx** [comment]
No it's random, reading the basic info (first call) is ok on the first time, any call after that is random. Here is a log from running every sec.

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828

entry 0x400806ac
JBD bms driver
Time:0:0:1
This capacity: 76.00
Current: 0.00
Voltage: 13.36
Protection state: 0
Cycle: 9
Temp1: 18.20
Temp2: 19.10

Number Of Cell: 4
Low: 3340
High: 3342
Diff: 2
Avg: 3341
Cell1: 3342
Cell2: 3341
Cell3: 3340
Cell4: 3342

Time:0:0:2
Basic: Communication error

Cell: Communication error

Time:0:0:3
Basic: Communication error

Number Of Cell: 4
Low: 3340
High: 3343
Diff: 3
Avg: 3341
Cell1: 3342
Cell2: 3341
Cell3: 3340
Cell4: 3343

Time:0:0:4
Basic: Communication error

Cell: Communication error

Time:0:0:5
Basic: Communication error

Number Of Cell: 4
Low: 3340
High: 3343
Diff: 3
Avg: 3341
Cell1: 3342
Cell2: 3341
Cell3: 3340
Cell4: 3343

Time:0:0:6
Basic: Communication error

Cell: Communication error

Time:0:0:7
Basic: Communication error

Number Of Cell: 4
Low: 3340
High: 3343
Diff: 3
Avg: 3341
Cell1: 3342

Cell2: 3341
Cell3: 3340
Cell4: 3343

Time:0:0:8
Basic: Communication error

Cell: Communication error

Time:0:0:9
Basic: Communication error

Number Of Cell: 4
Low: 3340
High: 3343
Diff: 3
Avg: 3341
Cell1: 3342
Cell2: 3341
Cell3: 3340
Cell4: 3343

Time:0:0:10
This capacity: 76.00
Current: 0.00
Voltage: 13.36
Protection state: 0
Cycle: 9
Temp1: 18.20
Temp2: 19.10

Number Of Cell: 4
Low: 3340
High: 3342
Diff: 2
Avg: 3341
Cell1: 3342
Cell2: 3341
Cell3: 3340
Cell4: 3342

**Comment by rahmaevao** [comment]
It might be worth extending the error codes to determine the error.
The error arises because the checksum did not converge.
This is possible due to:
1. Bms does not answer at all
2. BMS answers wrong (previous transfer did not end)
3. Reading the port of Yuart is not imposed from the first byte.

**Comment by boboxx** [comment]
Yes this is why I wanted to see the raw data of what was received and be able to display it, but I don’t know how to do this. This is my first project in c/c++ and Arduino.

**Comment by rahmaevao** [comment]
You need to make a print function for the "response" array in the readBmsData method.

**Comment by boboxx** [comment]
I was trying to return the array! I just added the serial.write in the readBmsData and readPackData. It's now clear that the return values do not start with 0xDD (221) and finish with 0x77 (119)

JBD bms driver
Time:0:0:1
221 3 0 27 5 55 0 0 80 239 109 96 0 9 39 131 0 0 0 0 0 0 21 74 3 4 2 11 78 11 92 251 194 119
This capacity: 74.00
Current: 0.00
Voltage: 13.35
Protection state: 0
Cycle: 9
Temp1: 16.30
Temp2: 17.70

221 4 0 8 13 13 13 10 13 10 13 12 255 151 119 0 0 0 42 0 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3338
High: 3341
Diff: 3
Avg: 3339
Cell1: 3341
Cell2: 3338
Cell3: 3338
Cell4: 3340
Time:0:0:2
252 63 1 0 0 0 10 0 0 0 128 29 0 0 10 13 13 13 3 0 11 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 12 13 10 13 9 13 12 255 153 119 31 251 63 101 47 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3337
High: 3340
Diff: 3
Avg: 3338
Cell1: 3340
Cell2: 3338
Cell3: 3337
Cell4: 3340

Time:0:0:3
252 63 1 0 0 0 10 0 0 0 128 29 0 0 9 13 12 13 3 0 10 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 12 13 10 13 9 13 12 255 153 119 31 251 63 205 94 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3337
High: 3340
Diff: 3
Avg: 3338
Cell1: 3340
Cell2: 3338
Cell3: 3337
Cell4: 3340

Time:0:0:4
252 63 1 0 0 0 10 0 0 0 128 29 0 0 9 13 12 13 3 0 10 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 13 13 10 13 10 13 12 255 151 119 31 251 63 53 142 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3338
High: 3341
Diff: 3
Avg: 3339
Cell1: 3341
Cell2: 3338
Time:0:0:5
252 63 1 0 0 0 10 0 0 0 128 29 0 0 10 13 13 13 3 0 11 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 12 13 10 13 10 13 12 255 152 119 31 251 63 157 189 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3338
High: 3340
Diff: 2
Avg: 3339
Cell1: 3340
Cell2: 3338
Cell3: 3338
Cell4: 3340

Time:0:0:6
252 63 1 0 0 0 10 0 0 0 64 29 0 0 10 13 12 13 2 0 11 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 13 13 10 13 10 13 12 255 151 119 31 251 63 4 237 0 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3338
High: 3341
Diff: 3
Avg: 3339
Cell1: 3341
Cell2: 3338
Cell3: 3338
Cell4: 3340

Time:0:0:7
252 63 1 0 0 0 10 0 0 0 64 29 0 0 10 13 13 13 3 0 11 13 88 64 13 128 96 31 251 63 40 2 252 63
Basic: Communication error

221 4 0 8 13 12 13 10 13 10 13 12 255 152 119 31 251 63 108 28 1 0 88 64 13 128 96 31 251 63 40 2 252 63
Number Of Cell: 4
Low: 3338
High: 3340
Diff: 2
Avg: 3339
Cell1: 3340
Cell2: 3338

**Comment by rahmaevao** [comment]
Well done
please output in hexadecimal form

**Comment by boboxx** [comment]
JBD bms driver
Time:0:0:1
DD 3 0 1B 5 37 0 0 50 EF 6D 60 0 9 27 83 0 0 0 0 0 0 15 4A 3 4 2 B 4E B 5C FB C2 77
This capacity: 74.00
Current: 0.00
Voltage: 13.35
Protection state: 0
Cycle: 9
Temp1: 16.30
Temp2: 17.70

DD 4 0 8 D D D A D A D C FF 97 77 0 0 0 1A 1F FB 3F 58 40 D 80 60 1F FB 3F 28 2 FC 3F
Number Of Cell: 4
Low: 3338
High: 3341
Diff: 3
Avg: 3339
Cell1: 3341
Cell2: 3338
Cell3: 3338
Cell4: 3340
Time:0:0:2
FC 3F 1 0 0 0 A 0 0 0 80 1D 0 0 A D D D 3 0 B D 58 40 D 80 60 1F FB 3F 28 2 FC 3F
Basic: Communication error

DD 4 0 8 D D D B D A D C FF 96 77 2F 0 0 1A 1F FB 3F 58 40 D 80 60 1F FB 3F 28 2 FC 3F
Number Of Cell: 4
Low: 3338
High: 3341
Diff: 3
Avg: 3339
Cell1: 3341
Cell2: 3339
Cell3: 3338
Cell4: 3340

Time:0:0:3
FC 3F 1 0 0 0 A 0 0 0 80 1D 0 0 A D D D 3 0 B D 58 40 D 80 60 1F FB 3F 28 2 FC 3F
Basic: Communication error

DD 4 0 8 D C D B D A D C FF 97 77 5F 0 0 1A 1F FB 3F 58 40 D 80 60 1F FB 3F 28 2 FC 3F
Number Of Cell: 4
Low: 3338
High: 3340
Diff: 2
Avg: 3339
Cell1: 3340
Cell2: 3339
Cell3: 3338
Cell4: 3340

**Comment by rahmaevao** [comment]
But is there an error if you do not use the function for reading voltage from cells?

**Comment by boboxx** [comment]
It looks like readPackData is returning a longer buffer than 34 int but get truncated, then it gets added to the beginning of readBmsData.

**Comment by boboxx** [comment]
if I only call readBmsData it's always ok.

DD 3 0 1B 5 37 0 0 50 EE 6D 60 0 9 27 83 0 0 0 0 0 0 15 4A 3 4 2 B 4D B 5D FB C3 77
This capacity: 74.00
Current: 0.00
Voltage: 13.35

Protection state: 0
Cycle: 9
Temp1: 16.20
Temp2: 17.80

**Comment by boboxx** [comment]
ah! BMS_LEN_RESPONCE is defined as 34 :)

**Comment by rahmaevao** [comment]
I thought about it.

**Comment by boboxx** [comment]
I added a pull request, not sure if it worked

**Comment by boboxx** [comment]
Finally found the problem! The array was not getting reinitialized. This was solved by:
uint8_t responce[BMS_LEN_RESPONCE] = {0x0};

0xDD 0x03 0x00 0x1B 0x05 0x36 0x00 0x00 0x50 0xD6 0x6D 0x60 0x00 0x09 0x27 0x83 0x00 0x00 0x00 0x00 0x00 0x00 0x15 0x4A 0x03 0x04 0x02 0xB 0x
57 0xB 0x62 0xFB 0xCD 0x77
This capacity: 74.00
Current: 0.00
Voltage: 13.34
Protection state: 0
Cycle: 9
Temp1: 17.20
Temp2: 18.30

0xDD 0x04 0x00 0x08 0xD 0xB 0xD 0x09 0xD 0x08 0xD 0x09 0xFF 0x9F 0x77 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0
x00 0x00 0x00 0x00 0x00
Number Of Cell: 4
Low: 3336
High: 3339
Diff: 3
Avg: 3337
Cell1: 3339
Cell2: 3337
Cell3: 3336
Cell4: 3337

I will clean up my code and upload a pull request.
