### ISSUE TITLE
How to connect wires to Arduino Mega?

### ISSUE THREAD

**Issue by rahmaevao** [rahmaevao/JbdBms#7]
Hi, I have loaded your code to my Ardunio Mega but I can't seem to get any data from my BMS. I only receive the following.

17:17:21.029 -> JBD bms driver
17:17:21.870 -> JBD bms driver
17:17:22.710 -> JBD bms driver
17:17:23.551 -> JBD bms driver
17:17:24.389 -> JBD bms driver
17:17:25.272 -> JBD bms driver
17:17:26.113 -> JBD bms driver
17:17:26.955 -> JBD bms driver

Are you able to confirm the correct wiring from the BMS to Arduino Mega. I'm current connecting RX to pin 10 , TX to pin 11 & ground to ground. I can communicate with my BMS via PC JDB Tools using the UART box but have no luck luck connecting to Arduino Mega. Do you have any pictures of the desired wiring please.

_Originally posted by @swarvie in https://github.com/rahmaevao/JbdBms/issues/2#issuecomment-803525186_

**Comment by rahmaevao** [comment]
Hello @swarvie.

1. Create a new issues if it arises. This will help other members of the community.
2. Connections of wires for UART, in theory, should be as follows:
```
RX -> TX
TX -> RX
GND -> GND
```
But for Chinese electronics, this is always a problem. The fact is that the Chinese can "help" and change the pin names.

Thus, if the wart does not work, always try to swap the TX and RX pins.

3. I cannot attach a photo, since I no longer have either the bms itself or the mega ardino on my hands.

4. Be sure to sign off on the result.

P.S. Write about other problems that you will encounter while working with my code.

**Comment by swarvie** [comment]
Thanks

I have tried to swap the pins but still the same issue. Could you please confirm that I need to connect the BMS directly to the Mega and nit via the UART box?

**Comment by rahmaevao** [comment]
You need to connect the bms directly without a box.

**Comment by swarvie** [comment]
Thanks, will update the outcome if I can get it to work.

**Comment by rahmaevao** [comment]
> Thanks I have tried to swap the pins but still the same issue. Could you please confirm that I need to connect the BMS directly to the Mega and nit via the UART box?
> […](#)
> Sent from my iPhone
> On 21 Mar 2021, at 6:59 pm, rahmaevao ***@***.***> wrote: ﻿ Hello @swarvie. Create a new issues if it arises. This will help other members of the community. Connections of wires for UART, in theory, should be as follows: RX -> TX TX -> RX GND -> GND But for Chinese electronics, this is always a problem. The fact is that the Chinese can "help" and change the pin names. Thus, if the wart does not work, always try to swap the TX and RX pins. I cannot attach a photo, since I no longer have either the bms itself or the mega ardino on my hands. Be sure to sign off on the result. P.S. Write about other problems that you will encounter while working with my code. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

In the week it will be possible to get bms and mega. I'll try too.

**Comment by rahmaevao** [comment]
I never got Mega, if you have such a controller, then try it and write down here about the results, thanks.
